all:
	g++ -std=c++11 main.cpp tester.cpp view.cpp subw_create_model.cpp fltk_controller.cpp customer.cpp subwindows.cpp easy_input.cpp order.cpp part_type.cpp robot_models.cpp robot_parts.cpp shop.cpp sales_associate.cpp date.cpp window_properties.h `fltk-config --ldflags --cxxflags --use-images` -s -o RRS_gui
