// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef test_h
#define test_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
Fl_Double_Window* make_window();
extern Fl_Menu_Item menu_[];
#endif
