#ifndef WINDOW_PROPERTIES_H
#define WINDOW_PROPERTIES_H 2016

#define HEIGHT 480
#define WIDTH 640
#define BORDER 10
#define MENUHEIGHT 30
#define TB_WIDTH 200
#define TB_HEIGHT 30
#define TB_SPACING 10

#endif