// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "test.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(750, 700);
    w = o;
    { Fl_Pack* o = new Fl_Pack(25, 25, 515, 430);
      { new Fl_Slider(50, 50, 25, 25);
      } // Fl_Slider* o
      { new Fl_Scrollbar(75, 50, 25, 25);
      } // Fl_Scrollbar* o
      { new Fl_Value_Slider(100, 50, 25, 25);
      } // Fl_Value_Slider* o
      { new Fl_Value_Slider(125, 50, 25, 25);
      } // Fl_Value_Slider* o
      { new Fl_Value_Output(150, 50, 25, 25);
      } // Fl_Value_Output* o
      { new Fl_Value_Input(175, 50, 25, 25);
      } // Fl_Value_Input* o
      { new Fl_Dial(200, 50, 25, 25);
      } // Fl_Dial* o
      { new Fl_Counter(225, 50, 25, 25);
      } // Fl_Counter* o
      { new Fl_Roller(250, 50, 25, 25);
      } // Fl_Roller* o
      o->end();
    } // Fl_Pack* o
    { Fl_Table* o = new Fl_Table(25, 25, 515, 430);
      o->end();
    } // Fl_Table* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
