all:
	g++ -std=c++11 main.cpp tester.cpp fileio.cpp view.cpp controller.cpp customer.cpp easy_input.cpp order.cpp part_type.cpp robot_models.cpp robot_parts.cpp shop.cpp sales_associate.cpp -o RRS_Executable

